#!/bin/bash
# Simple Script to fix NO_PUBKEY
# by Richard Hanz Kalaw
# email scott_rk@yahoo.com
# web http://projectrk.com.ph
#
echo "Simple NO_PUBKEY Fix"
echo
read -p 'Input NO_PUBKEY: ' pubkey
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $pubkey
echo "Done... "
